### ISSUE TITLE
electron not found

### ISSUE THREAD

**Issue by rehmm070304** [supechicken/ChromeOS-Desktop#2]
when i run the command npm start, it says

 ChromeOS Desktop@0.1 start
> electron . --ozone-platform-hint=wayland

sh: 1: electron: not found

**Comment by rehmm070304** [comment]
ChromeOS Desktop@0.1 start
 electron . --ozone-platform-hint=wayland

sh: 1: electron: not found

**Comment by sometgirldotonline** [comment]
you need to run `npm -i electron --save-dev`

**Comment by rehmm070304** [comment]
when i put that in:
Unknown command: "electron"

**Comment by rehmm070304** [comment]
no i fixed it
